language: ruby
rvm:
  - 2.2.6
branches:
  - master
jobs:
  include:
    - stage: Start
      script: skip
    - stage: Deploy
      script: skip
      deploy:
        skip_cleanup: true
        provider: heroku
        api_key:
          secure: $HEROKU_API_KEY
        on: master
        app: resushi
      after_deploy:
        run:
          - "heroku pg:reset DATABASE_URL"
          - "rake db:migrate"
          - restart
          - "rake db:seed"