language: ruby
rvm:
  - 2.2.6
branches:
  - master
sudo: required
before_script:
  # this install.sh script requires sudo
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
jobs:
  include:
    - stage: Start
      script: skip
    - stage: Deploy
      script: skip
      deploy: &heroku
        skip_cleanup: true
        provider: heroku
        api_key:
          secure: $HEROKU_API_KEY
        on: master
        app: resushi
        run:
          - "pg:reset DATABASE_URL"
          - "rake db:migrate"
          - "rake db:seed"